language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - mongodb
addons:
  code_climate:
    repo_token: db8e0401a58f09ed237620304610a93a63dd4f4983175a7f7e73dcc8891e3f6e
